# Site settings
title: Saurav Kumar
description: Saurav personal website
#baseurl: ""  # the subpath of your site, e.g./blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Saurav Kumar
user_description: 
user_title: Life Engineer
email: sauravkumar.iitkgp@gmail.com
# twitter_username: lorem_ipsum
instagram_username: sauravwellbeing
facebook_username: saurav.wellnesscoach
linkedin_username: saurav-kumar-897680130
github_username:  sauravwel
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
